jobs:
  include:
    - stage: "Documentation"
      julia: 1.9
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success:
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
        - uses: codecov/codecov-action@v1

    - stage: "Deployment"
      language: julia
      os: linux
      julia: 1.9.0
      notifications:
        email: true
      sudo: false
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
