language: julia  # Primary language is Julia

branches:
  only:
    - master  # Only run CI/CD workflows on the master branch

jobs:
  include:

    - stage: "Test and Coverage"
      julia: 1.10.7
      os: linux
      script:
        - julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test(coverage=true)'
        - bash <(curl -s https://codecov.io/bash)  # Submitting to Codecov

    - stage: "Documentation"
      julia: 1.10.7
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ --code-coverage=user docs/make.jl

    - stage: "Deployment"
      os: linux
      language: julia
      julia: 1.10.7
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
