name: Codecov

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.9.2'
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests with coverage
        env:
          JULIA_COVERAGE: true
        run: julia --project=. -e 'using Pkg; Pkg.test(coverage=true)'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          commit: HEAD~5..HEAD
